### ISSUE TITLE
some errors/crash after running for a little while

### ISSUE THREAD

**Issue by shejk0** [NecronomiconCoding/Pokemon-Go-Rocket-API#13]
crashing on ptc & google

[03:48:19] We caught a Eevee with CP 163

Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Google.Protobuf.Collections.RepeatedField`1.get_Item(Int32 index)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\dowd1\Desktop\Pokemon-Go-Rocket-API\Accounts\Ptc-1\PokemonGo\RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__24.MoveNext() in C:\Users\dowd1\Desktop\Pokemon-Go-Rocket-API\Accounts\Ptc-1\PokemonGo\RocketAPI\Client.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Console.Program.<ExecuteCatchAllNearbyPokemons>d__6.MoveNext() in C:\Users\dowd1\Desktop\Pokemon-Go-Rocket-API\Accounts\Ptc-1\PokemonGo\RocketAPI\Console\Program.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Console.Program.<ExecuteFarmingPokestopsAndPokemons>d__7.MoveNext() in C:\Users\dowd1\Desktop\Pokemon-Go-Rocket-API\Accounts\Ptc-1\PokemonGo\RocketAPI\Console\Program.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Console.Program.<Execute>d__5.MoveNext() in C:\Users\dowd1\Desktop\Pokemon-Go-Rocket-API\Accounts\Ptc-1\PokemonGo\RocketAPI\Console\Program.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by knoxz** [comment]
Same error here.

**Comment by Yixn** [comment]
Yep would love to see this one resolved too :D

**Comment by Hardell** [comment]
This was fixed already.
